### PR TITLE
Rewrite site-menu css

### PR DESCRIPTION
**Pull request by melaniebmn**
# Summary | Résumé

CSS rewrite for the site-menu component.

### CODE REVIEW

**Comment by ethanWallace** [comment]
This is fantastic! Just noticed a few small things, I am going to put them all in this comment.

Not all elements with `role="menuitem"` are `<a>` tags. The menu also accepts `<span>` tags as menu items. If a span is used it currently renders like this: 

Screen Shot 2022-05-09 at 3 32 53 PM

Looks like a `align-items: center; display: flex;` could fix the issue.

---

When rendering topbar, if focused on the top-level menu item the submenu trigger button text turns white, creating a colour contrast issue.

Screen Shot 2022-05-09 at 3 27 20 PM

---

And lastly, this may come down to a token issue. I noticed the container size is really large, I believe it was this size before Nick adding styling to the site-menu. I am wondering do we adjust the tokens or do we make an easy way for someone to adjust the container width (StyleAPI)?

**Comment by melaniebmn** [comment]
@ethanWallace fixed the two issues you found, thanks for pointing them out.
The container size is currently the same as the container size we are using on the docs page. I agree, it is quite big and we should give users the ability to change it. We could either do StyleAPI or we could add a `containerSize` prop that lets them select any of our supported container sizes. What do you think?

**Comment by ethanWallace** [comment]
> @ethanWallace fixed the two issues you found, thanks for pointing them out. The container size is currently the same as the container size we are using on the docs page. I agree, it is quite big and we should give users the ability to change it. We could either do StyleAPI or we could add a `containerSize` prop that lets them select any of our supported container sizes. What do you think?

I think it would be best as a styleAPI property. Something like `customContainerWidth` could set the max width of the container.

**Comment by melaniebmn** [comment]
@ethanWallace I'll add it as part of the sidebar changes since it's more of a feature than a rewrite.

**Pull request merged**
