### PR TITLE
add gcds-file-uploader component

### PR DESCRIPTION
**Pull request by melaniebmn**
# Summary | Résumé

Add gcds-file-uploader component.

The file uploader allows users to upload one or multiple files to a specific location.

### CODE REVIEW

**Review by ethanWallace — COMMENTED** [review]
It looks good! The only thing I see is making it bilingual and it should be good to go.

**Comment by melaniebmn** [comment]
> It looks good! The only thing I see is making it bilingual and it should be good to go.

Yikes, can't believe I forgot that - thanks for pointing it out!

**Comment by melaniebmn** [comment]
@ethanWallace added french translations for everything.

**Comment by ethanWallace** [comment]
Just noticed something small on my last look over, would you be able to add the onBlur event that the other inputs have? It's something the validators will take advantage of.

**Comment by melaniebmn** [comment]
@ethanWallace good catch, I added the onBlur and onFocus events.

**Review by ethanWallace — APPROVED** [review]
LGTM!

**Pull request merged**
