### PR TITLE
feat: update components with new typography + spacing tokens

### PR DESCRIPTION
**Pull request by melaniebmn**
# Summary | Résumé

PR to support the update of our typography and spacing tokens in [PR #345](https://github.com/cds-snc/gcds-tokens/pull/345).

## Included changes
- Updated margin + padding props to include new spacing values for the container, heading, icon, and text components.
- Adjusted the default margin + padding values to match new spacing values for the container, heading, icon, and text components.
- Adjusted the heading, icon, and text margin + padding in other components.
- Adjusted the topic menu styling.
- Fixed the input size calculation.
- Adjusted the breadcrumbs styling ([ticket](https://app.zenhub.com/workspaces/design-system-6100624a19f4cf000e46e458/issues/gh/cds-snc/design-gc-conception/1281)).
- Adjusted the card styling ([ticket](https://app.zenhub.com/workspaces/design-system-6100624a19f4cf000e46e458/issues/gh/cds-snc/design-gc-conception/1281)).

## Breaking changes
 - Container `margin` + `padding` values changed.
 - Heading `margin-top` + `margin-bottom` values changed.
 - Icon `margin-left` + `margin-right` values changed.
 - Text `margin-top` + `margin-bottom` values changed.
 - Renamed text size `caption` to `small` to align with the global `text-small` font token.
 - Renamed icon size `caption` to `text-small` to align with the global `text-small` font token.

[Zenhub ticket](https://app.zenhub.com/workspaces/design-system-6100624a19f4cf000e46e458/issues/gh/cds-snc/design-gc-conception/1277)

## Note
Needs  [PR #345](https://github.com/cds-snc/gcds-tokens/pull/345) merged + token package updated before this PR can be merged.

### CODE REVIEW

**Comment by daine** [comment]
Could we change the title (and commit name) to conventional commit format

**Comment by ethanWallace** [comment]
We will need to update the way we set `max-width` with the `size` attribute in the `gcds-input`,[ this line](https://github.com/cds-snc/gcds-components/blob/update-with-new-tokens/packages/web/src/components/gcds-input/gcds-input.tsx#L361). Since the padding token is no longer a single value that line breaks. It can probably be rewritten as `calc(${size * 2}ch + 1.5rem)` to make it work again.

**Comment by ethanWallace** [comment]
Do we want to change the spacing values used for form elements like the labels/hints/error messages? As you can see below the new line height adds some extra spacing to those form elements, mainly noticeable between the label and hint.

Screenshot 2024-12-03 at 9 32 27 AM

**Comment by melaniebmn** [comment]
> Could we change the title (and commit name) to conventional commit format

Yes, sorry started this as a test PR and then forgot to change the title.

**Comment by ethanWallace** [comment]
Looks like we will have to update the `margin-bottom` attribute that is used on  a `gcds-text` component in `gcds-error-message`, it is currently set to `300`.

**Comment by melaniebmn** [comment]
> Looks like we will have to update the `margin-bottom` attribute that is used on a `gcds-text` component in `gcds-error-message`, it is currently set to `300`.

Great catch, thanks @ethanWallace! Updated the error message and other components.

**Review by daine — COMMENTED** [review]
Could we change the conventional commit to either say `feat: ` or `fix: ` because this is not a refactor? Thank you!

**Review by ethanWallace — APPROVED** [review]
LGTM!

**Review by daine — APPROVED** [review]
🚀 LGTM

**Pull request merged**
