### PR TITLE
update alert design + tokens

### PR DESCRIPTION
**Pull request by melaniebmn**
# Summary | Résumé

Update alert design + add new tokens.
- Added a new prop to hide the role icon.
- Renamed "max-content-width" prop to "container" for better consistency with other components.

### CODE REVIEW

**Comment by amazingphilippe** [comment]
>  Why do we not use our usual outline focus

We can definitely use our usual outline focus. Good point. Looking at this, why don't we also give a bit more contrast to those buttons either on hover or on default?

image

**Comment by amazingphilippe** [comment]
Another option: 
image

With prototype: https://www.figma.com/proto/mh2maMG2NBtk41k1O1UGHV/GC-Components-Main?page-id=885%3A2249&node-id=2928%3A11518&viewport=590%2C-140%2C0.39&scaling=min-zoom

**Comment by ethanWallace** [comment]
I meant a focus state more like the button we have, just to keep the focus states consistent when we use buttons. See below:

Screen Shot 2023-01-26 at 4 22 24 PM

I don't think every other state requires a redesign

**Comment by amazingphilippe** [comment]
Oh I see what you mean. We just missed the extra border: 
image

**Pull request merged**
