### PR TITLE
remove button-style prop from button component

### PR DESCRIPTION
**Pull request by melaniebmn**
# Summary | Résumé

Small refactor of the button component. Since we are adding a `gcds-link` component, we decided to discontinue support for a `text-only` button style for the `gcds-button` component.

This PR is removing the `button-style` prop, as well as both icon slots that are not needed.

Notes BEFORE merging:
- This PR can't be merged until the `gcds-link` component + its guidance is live.
- Once the `gcds-link` component PR is merged, this PR needs to be updated. We need to replace all `text-only` buttons in the resources section of each overview tab on Storybook with the `gcds-link` before merging.

[Tokens PR](https://github.com/cds-snc/gcds-tokens/pull/199)

### CODE REVIEW

**Comment by daine** [comment]
LGTM; will approve once Link component is live

**Comment by daine** [comment]
Could we resolve the conflicts? Thank you ✨

**Comment by melaniebmn** [comment]
> Could we resolve the conflicts? Thank you ✨

@daine I'm going to hold off until the updated guidance for the buttons and the guidance for the link component is ready. We can't really merge this before, unfortunately. :(

**Comment by melaniebmn** [comment]
Closing this PR in favor of [#408 ](https://github.com/cds-snc/gcds-components/pull/408).

**Pull request closed without merging**
